# -*- coding: utf-8 -*-
"""final project midi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MyorON4BoL5kWeEjNX8WMDlFbi44W6lD
"""

from music21 import *
from IPython.display import Image, Audio
import math

!apt-get install lilypond > /dev/null

def show(music):
  display(Image(str(music.write('lily.png'))))

from google.colab import files
uploaded = files.upload()
#myFile = converter.parse("project midi.mid")
myFile = converter.parse("Happy-Birthday-To-You-1.mid")
#myFile.flat.show("text")

VoicePart1 = "Two roads diverged in a yellow wood,And sorry I could not travel bothAnd be one traveler, long I stoodAnd looked down one as far as I couldTo where it bent in the undergrowth;"
VoicePart2 = "Then took the other, as just as fair,And having perhaps the better claim,Because it was grassy and wanted wear;Though as for that the passing thereHad worn them really about the same,"
VoicePart3 = "And both that morning equally layIn leaves no step had trodden black.Oh, I kept the first for another day!Yet knowing how way leads on to way,I doubted if I should ever come back."
VoicePart4 = "I shall be telling this with a sighSomewhere ages and ages hence:Two roads diverged in a wood, and I—I took the one less traveled by,And that has made all the difference."

from hashlib import sha256
import random
import copy
s1 = stream.Part()
instru1 = instrument.Harp()
s1.insert(0, instru1)
s2 = stream.Part()
instru2 = instrument.Marimba()
s2.insert(0, instru2)
s3 = stream.Part()
instru3 = instrument.Piano()
s3.insert(0, instru3)
s4 = stream.Part()
instru4 = instrument.Guitar()
s4.insert(0, instru4)
nScore = stream.Score()
tmplist = myFile.flat
for i in range(len(VoicePart1)):
  picked_idx = ord(VoicePart1[i])
  if picked_idx>398:
    continue
  new_item = copy.deepcopy(tmplist[picked_idx])
  s1.append(new_item)
for i in range(len(VoicePart2)):
  picked_idx = ord(VoicePart2[i])
  if picked_idx>398:
    continue
  new_item = copy.deepcopy(tmplist[picked_idx])
  s2.append(new_item)
for i in range(len(VoicePart3)):
  picked_idx = ord(VoicePart3[i])
  if picked_idx>398:
    continue
  new_item = copy.deepcopy(tmplist[picked_idx])
  s3.append(new_item)
for i in range(len(VoicePart4)):
  picked_idx = ord(VoicePart4[i])
  if picked_idx>398:
    continue
  new_item = copy.deepcopy(tmplist[picked_idx])
  s4.append(new_item)
nScore.insert(0,s1)
nScore.insert(0,s2)
nScore.insert(0,s3)
nScore.insert(0,s4)
#s.flat.show("text")

from google.colab import files
filename = 'myMIDI' + '.mid'
fp = nScore.write('mid', fp=filename)
files.download('myMIDI.mid')